version: "3"
services:
  nginx:
    build:
      context: .
      args:
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_VERSION: nginx:${NGINX_VERSION}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
    volumes:
      - ${NGINX_ETC_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_ETC_DIR}/conf.d:/etc/nginx/conf.d/:ro
      - ${NGINX_ETC_DIR}/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_ETC_DIR}/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ${NGINX_ETC_DIR}/ssl:/ssl:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${ROOT_PATH}:/www/:rw
    environment:
      TZ: "${TZ}"
    restart: ${NGINX_RESTART_POLICY}
    networks:
      - dev
networks:
  dev:
    external: true
